# base
FROM node:20-alpine3.22 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN apk add --no-cache libc6-compat openssl ca-certificates libressl && npm install -g pnpm &&  pnpm install turbo --global
RUN update-ca-certificates

# prune monorepo
FROM base AS pruner
WORKDIR /app
COPY . .
RUN turbo prune web --docker

# install dependencies
FROM base AS installer
WORKDIR /app
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN pnpm install --frozen-lockfile

# build
FROM base AS builder
WORKDIR /app
COPY --from=installer /app .
COPY --from=pruner /app/out/full .
COPY turbo.json turbo.json
RUN pnpm --filter=@brain-cache/db prisma generate
RUN pnpm turbo build --filter=web...

# runtime
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder --chown=nextjs:nodejs  /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs  /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder --chown=nextjs:nodejs  /app/apps/web/public ./apps/web/public

EXPOSE 3000

CMD ["node", "apps/web/server.js"]